# ---------------------------
# Server Configuration
# ---------------------------
spring.application.name=erp-report
server.port=8761



# ---------------------------
# MySQL Database Configuration
# ---------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/erp_report?useSSL=false&serverTimezone=UTC
spring.datasource.username=mukesh
spring.datasource.password=mukesh@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ---------------------------
# JPA Configuration (If Using JPA)
# ---------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ---------------------------
# Eureka Client Configuration
# ---------------------------
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/

# spring.session.store-type=jdbc
# Automatically create Spring Session JDBC tables if they do not exist
spring.session.jdbc.initialize-schema=always